; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27023.1 

	TITLE	G:\내 드라이브\SOURCE\CPP\1\SECTION7\mangling2.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	_square
PUBLIC	_main
; Function compile flags: /Odtp
; File g:\내 드라이브\source\cpp\1\section7\mangling2.cpp
_TEXT	SEGMENT
_main	PROC

; 7    : {

	push	ebp
	mov	ebp, esp

; 8    :     square(3);

	push	3
	call	_square
	add	esp, 4

; 9    : 
; 10   : }

	xor	eax, eax
	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
; File g:\내 드라이브\source\cpp\1\section7\mangling2.cpp
_TEXT	SEGMENT
_a$ = 8							; size = 4
_square	PROC

; 2    : {

	push	ebp
	mov	ebp, esp

; 3    :     return a * a;

	mov	eax, DWORD PTR _a$[ebp]
	imul	eax, DWORD PTR _a$[ebp]

; 4    : }

	pop	ebp
	ret	0
_square	ENDP
_TEXT	ENDS
END
