; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27023.1 

	TITLE	G:\내 드라이브\SOURCE\CPP\1\SECTION7\mangling1.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	?square@@YAHH@Z					; square
PUBLIC	?square@@YANN@Z					; square
PUBLIC	_main
PUBLIC	__real@400a666666666666
EXTRN	__fltused:DWORD
;	COMDAT __real@400a666666666666
CONST	SEGMENT
__real@400a666666666666 DQ 0400a666666666666r	; 3.3
CONST	ENDS
; Function compile flags: /Odtp
; File g:\내 드라이브\source\cpp\1\section7\mangling1.cpp
_TEXT	SEGMENT
_main	PROC

; 12   : {

	push	ebp
	mov	ebp, esp

; 13   :     square(3);

	push	3
	call	?square@@YAHH@Z				; square

; 14   :     square(3.3);

	add	esp, -4					; fffffffcH
	movsd	xmm0, QWORD PTR __real@400a666666666666
	movsd	QWORD PTR [esp], xmm0
	call	?square@@YANN@Z				; square
	fstp	ST(0)
	add	esp, 8

; 15   : }

	xor	eax, eax
	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
; File g:\내 드라이브\source\cpp\1\section7\mangling1.cpp
_TEXT	SEGMENT
tv67 = -8						; size = 8
_a$ = 8							; size = 8
?square@@YANN@Z PROC					; square

; 7    : {

	push	ebp
	mov	ebp, esp
	sub	esp, 8

; 8    :     return a * a;

	movsd	xmm0, QWORD PTR _a$[ebp]
	mulsd	xmm0, QWORD PTR _a$[ebp]
	movsd	QWORD PTR tv67[ebp], xmm0
	fld	QWORD PTR tv67[ebp]

; 9    : }

	mov	esp, ebp
	pop	ebp
	ret	0
?square@@YANN@Z ENDP					; square
_TEXT	ENDS
; Function compile flags: /Odtp
; File g:\내 드라이브\source\cpp\1\section7\mangling1.cpp
_TEXT	SEGMENT
_a$ = 8							; size = 4
?square@@YAHH@Z PROC					; square

; 2    : {

	push	ebp
	mov	ebp, esp

; 3    :     return a * a;

	mov	eax, DWORD PTR _a$[ebp]
	imul	eax, DWORD PTR _a$[ebp]

; 4    : }

	pop	ebp
	ret	0
?square@@YAHH@Z ENDP					; square
_TEXT	ENDS
END
